### PR TITLE
Some suggested changes

### PR DESCRIPTION
**Pull request by robert-ancell**

### CODE REVIEW

**Review by olivercalder — APPROVED** [review]
Thank you @robert-ancell for the feedback, these all look great!

**Comment by olivercalder** [comment]
I was using the `name` parameter based on the existing snapd API, but I realize if we need to use the `snap` and `app` identifiers instead, there are several other places where this is presumably also the case:

https://github.com/robert-ancell/snapd-prompt-api-brainstorming/blob/8d5f643d8250752af73b24cdb14e3a958358b1d8/openapi.yaml#L109-L129

https://github.com/robert-ancell/snapd-prompt-api-brainstorming/blob/8d5f643d8250752af73b24cdb14e3a958358b1d8/openapi.yaml#L151-L176

https://github.com/robert-ancell/snapd-prompt-api-brainstorming/blob/8d5f643d8250752af73b24cdb14e3a958358b1d8/openapi.yaml#L369-L395

However, doesn't the existing label system already accomplish identifying both snap and app? For example, `"snap.matternost-desktop.mattermost-desktop"` identifies the `mattermost-desktop` app inside the `mattermost-desktop` snap. Would splitting these up into two parameters for snap and app increase clarity for the end user? Else I would think using only one parameter with the full label (e.g. `"snap.mattermost-desktop.mattermost-desktop"`) would be preferable.

**Comment by robert-ancell** [comment]
It would be safer to be explicit in the API, and then clients don't need to split out the name and handle error cases if it's not valid. It makes sense for a command line UI like 'snap run' to combine these. In a graphical UI, we're unlikely to use the same convention.

**Comment by olivercalder** [comment]
Thanks @robert-ancell 

I've opened a new PR which I hope implements what you are looking for: https://github.com/olivercalder/snapd-prompt-api-brainstorming/pull/3

**Pull request merged**
